### ISSUE TITLE
Optional email notifications

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#117]
- [x] When a new RFC was created
- [ ] When a new argument was added to an RFC you follow (this should be a digest mail, once a week)

**Comment by vsergiu93** [comment]
I'll be honest, I would like this issue to be addressed in a future stream, I would like to see how you would approach this, basically at first this issue seems easy but the more you think about it the more you realized there are a few things that have to be addressed, or at least that's the way I see it.

Maybe I'm overthinking it, I don't know.

Here are a few concerns/unknowns from me:
1. We want to send a email notification when a rfc is created, which is fine, but the problem is what if in the span of couple of minutes 2+ rfc were created should I get an email for each one of them or should we buffer all of this and send and email with all the newly created rfc? I would prefer the second option as it feels more clean and it will not spam the user. (it could be that this is an extreme edge case, and is not worth putting a lot of effort in to it.)
2. Second requirement is a bit confusing for me, should we send the email as soon as the argument was created or? If we want to send as soon as an argument is created I guess the concerns from point 1 makes sense here as well.
3. As I was writing this comment, I realized that we also need a good approach to allow users to selectively opt in/out on this email notifications. I guess here we think of the case where I don't want to get this weekly emails, but I do want to get notified when new arguments are added to any of the rfc where I voted/subscribed.
4. We also need to figure out what content each type of notification should contain.
5. Also isn't there an option to set an end date for an RFC? I remember seeing it in the rfc creation form, shouldn't we also send a notification when an rfc is closed? Maybe I misunderstood what this end date means, but if it means that at the specified date the voting is closed, then it would be nice to send a notification to all users who subscribed to that rfc. The email could contain the final results and maybe the top x arguments.
6. Another thing would be to allow users to subscribe to rfc without being required to actually vote on the rfc. I'm thinking here of the case where I don't really have anything to say about an rfc, but I'm still curious about what others think about it.

If no one takes this, I think it could be a good issue to address on a stream. Not sure if what I wrote above makes sense or is just me overthinking it :).

**Comment by brendt** [comment]
It's definitely a complex issue 😅 I will address it on stream :)

**Comment by brendt** [comment]
Ok, so an update from my side. I've pushed and deployed a very simple implementation to production, that will only send mails when new RFCs are created,  and only for users that have opted-in. 

This is a first test, if this runs smooth, we can look at all the edge cases — I will stream that part, I didn't stream anything today because I wanted to focus :)

**Comment by BobDankert** [comment]
Another notification I would love to be able to get would be the result of an RFC vote, after it has taken place (for RFC's where the vote hasn't occurred already)

**Comment by brendt** [comment]
I suppose you're talking about the official RFC vote result, right?

**Comment by BobDankert** [comment]
Correct - the official RFC Vote result. Something along the lines of "Hello! This PHP RFC has completed official voting, and here are the results"

**Comment by brendt** [comment]
Agree, that would be useful. Thanks for suggesting!

**Comment by brendt** [comment]
Followup: I'm introducing the concept of "messages" in https://github.com/brendt/rfc-vote/issues/107 Messages are in-app notifications. However, we could use them to send a weekly digest: if you have unread messages, we'll send an email once a week. 

This way we don't need to hook into any other parts of the app, making it significantly easier.

**Comment by brendt** [comment]
Gonna close this one, as we'll use in-app messages and digest mails in the future.
