### ISSUE TITLE
Username must be valid

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#144]
> The [register form](https://rfc.stitcher.io/register) on the RFC voting website indicates 'The username must be valid', what does that mean?
> I tried a few different ones, but I keep getting the same message. What are the username requirements?

**Comment by vsergiu93** [comment]
Yeah, I should have added a better error message :), Basically I created that custom rule app/Rules/UsernameFormatRule.php, which basically just makes sure that you have send a valid username.

What I wanted with this is to force users to write a username which follows some conventions.

I think we do need this validation or something similar, we want all the usernames to follow certain conventions. but at the same time we need to improve the UX a bit.

Right now I see two possible solutions:
- Improve the error message, `Username must follow this pattern (regex partern here for Str:slug())` or `Username does not allow for spaces ....` 
- Add a description under the username field which describe the accepted pattern, something like this: 
![image](https://github.com/brendt/rfc-vote/assets/5923843/7b688934-d1d4-4203-b3b1-4f685b5d4cb8)

But I'm open to other suggestions, also since I worked on this I'm more than happy work on this, I just need some guidance, I'm not really that good at UX/UI.

**Comment by brendt** [comment]
In this case, the user wrote a username with uppercase letters. I think it's best to allow some more input, and simply call strtolower on it when we save the username.

A slightly better error message would be welcome as well.

Do you want to take a look at it? If not I'll fix it :)

**Comment by vsergiu93** [comment]
Yes, sure. 
One thing, usually I don't really like modifying user input for register forms. If we want to allow more variations in usernames maybe then we should change the rule, for example allow uppercase letters in usernames.

Basically I agree that what we have now is terrible, users have no idea what is allowed and what not, but not sure if automatically converting the username to lowercase is the best approach here.

Ok, I'll work today on this, I'll try to come up with a proposal and then we can discuss more if needed.

I will focus on this: 
- Improve validation message for username ( this already will improve the UX) 
- Maybe add some sort of requirements description under the input (as shown in my previous message), informing the users about the username validation.
- Maybe we can make a liveware component which validates the input as you type and adding some visual feedback when the username is valid or invalid.

**Comment by brendt** [comment]
Sounds perfect, thanks for looking into it!

**Comment by vsergiu93** [comment]
I worked a bit on this, made some progress, just need to see if I can improve the code a bit.
Here is a preview of how it looks like:

https://github.com/brendt/rfc-vote/assets/5923843/facaa079-d0a9-4e6e-818b-f3b310dec5f2

**Comment by brendt** [comment]
Looks great!

**Comment by vsergiu93** [comment]
@brendt I marked the PR as ready for CR, left some comments myself, there are a few things I don't really like and I would gladly accept some suggestions/ideas. 
Thanks
