### ISSUE TITLE
Two-column layout

### ISSUE THREAD

**Issue by olleharstedt** [brendt/rfc-vote#148]
Dunno if it's a good idea, but it's _one_ idea: to split the pros and cons arguments in two columns next to each other for better overview.

**Comment by SerhiiCho** [comment]
I like this idea @olleharstedt, I've tried to it and it looked great, the only problem that I have with CSS is that on the mobile view, "yes" arguments are at the top and "no" arguments at the bottom.

I was looking for way to make it work so that on mobile we have them mixed up, but even Chat GPT wasn't been able to help. I'll think how you can do it, this was the original idea of @brendt to make it into 2 colums

**Comment by olleharstedt** [comment]
You're not using a CSS framework with columns?

**Comment by SerhiiCho** [comment]
> You're not using a CSS framework with columns?

I do, there is tailwindcss already in the project

**Comment by vsergiu93** [comment]
@SerhiiCho I think it's possible with grid quite easy, not really sure how to do this with tailwind though.
Basically with grid-column-start, you can control on which column certain arguments will be placed then on mobile you just remove the second column and let them render normally as they are in html.

**Comment by SerhiiCho** [comment]
@vsergiu93 Yeah, I've tried this too. It leaves lots of empty space like this:
![image](https://github.com/brendt/rfc-vote/assets/35465417/e0c5697b-1438-48ae-adac-25dbd845043f)
There has to be a way to get rid of empty space

**Comment by SerhiiCho** [comment]
Here is another example of how it leaves a space:
![image](https://github.com/brendt/rfc-vote/assets/35465417/6f3d4c2b-7d7b-4dac-a339-b3314caf7d48)

**Comment by SerhiiCho** [comment]
I have one idea, I'll make it work. Since grid splits everything in rows, there is no way to get rid of that empty space, so I'll split arguments into 2 collections, 'yes' and 'no', and put in 1 grid row 1 'yes' argument and 1 'no' argument.

**Comment by vsergiu93** [comment]
@SerhiiCho You are right, sorry, I guess for this to work with css grid we would need this [Masonry layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout) :).

**Comment by SerhiiCho** [comment]
> we would need this [Masonry layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout) :).

Never heard of it, I'll check it out. Thanks 🙏

**Comment by SerhiiCho** [comment]
I can do something like this:

![Screen Recording 2023-08-23 at 12 17 26](https://github.com/brendt/rfc-vote/assets/35465417/b516b080-ad20-4d95-add0-3cd013f5b124)

Then, on mobile version we'll have 1 yes, followed by 1 no, followed by 1 yes, etc.

**Comment by brendt** [comment]
Does this approach use grouping argument per vote type? I wonder how that would impact sorting on mobile?

**Comment by SerhiiCho** [comment]
> I wonder how that would impact sorting on mobile?

There won't be any problems with sorting, since we:

1. Search for arguments
2. Fetch them from DB
3. Split them into 2 groups
4. Display them

**Comment by brendt** [comment]
Let's think out of the box for a moment. The reason we can't go with a simply 2-grid layout is because of mobile styling, right? If all yes arguments are in the left column, and all no arguments in the right, then all yes arguments will end on top as soon as we switch to a one column layout on mobile.

What if… we drop mobile support 😎

No, just kidding. What if we work with some kind of tab view on mobile, where you can switch between yes or no arguments, essentially keeping the 2 column layout, but simply having one invisible.

I know it's not ideal, but I don't think the gaps are ideal either.

Another approach: if we decide to keep the gaps, then I think it'd be better to fully embrace it, and not put a yes/no argument on the same line. I mean that we can add `mr-[50%]` to the yes cards, and `ml-[50%]` to the no cards (or 45% or 60%, whatever looks best). I actually think this might be a good approach now that I'm writing it. I do like the dotted line that fills the whitespace, would be cool if we could combine the two.

Anyway, I'm just brain-dumping, we can take a different approach if people don't like these ideas.

**Comment by SerhiiCho** [comment]
> What if… we drop mobile support 😎

Great idea 😄

> I mean that we can add mr-[50%] to the yes cards, and ml-[50%] to the no cards (or 45% or 60%, whatever looks best)

You mean make it like a chess board?

```
yes
      no
yes
      no
yes
      no
```

**Comment by brendt** [comment]
> You mean make it like a chess board?

Exactly, and fill the gaps with the dotted line you've proposed — if possible

**Comment by SerhiiCho** [comment]
You think it looks better now?

![Screen Recording 2023-08-24 at 12 31 18](https://github.com/brendt/rfc-vote/assets/35465417/232557ce-246b-4dae-ab22-553c85f109d9)

**Comment by brendt** [comment]
I'm not sure if it's better or not 🫥. What do you think? Maybe we could experiment with the block overlapping a bit?

```
====== 
   YES
======
          ======
              NO
          ======
```

**Comment by SerhiiCho** [comment]
![Screen Recording 2023-08-24 at 15 35 48](https://github.com/brendt/rfc-vote/assets/35465417/0878feb4-f21d-4469-928b-433d789f0e73)

**Comment by SerhiiCho** [comment]
I don't know, I'll think about something simpler

**Comment by brendt** [comment]
I definitely think the dotted lines add value 💯

Personally, I like this last edition the most, but feel free to iterate on it some more :)

**Comment by Plytas** [comment]
> ![image](https://user-images.githubusercontent.com/35465417/262977298-1f83efc3-606b-4f85-bccd-dbf941a5497b.png)

Would it make sense in this case for `NO` arguments to put vote button on the right? It might interfere with the tripple dot menu, but it's just an idea to play around with. On mobile it would almost feel like swiping left/right.

**Comment by brendt** [comment]
I actually did that in the very first draft. I'm open for it, but I'm no designer. I feel @SerhiiCho has a say in it as well, since he's been doing most of the frontend stuff.

**Comment by SerhiiCho** [comment]
I have tried it, it looks odd to me when ellipsis on the top-left corner

**Comment by SerhiiCho** [comment]
I'll try it again

**Comment by SerhiiCho** [comment]
I'm unable to do that, the Livewire is getting in the way all the time, its performance is awful. If we were using something like Vue I would have no problems. With Livewire, I'm getting the memory issue when trying to split arguments into 2 separate collections.
