### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#168]
We need a dedicated page that lists all contributors, and thank them.

**Comment by SerhiiCho** [comment]
You can take it easy with styles if you want, I'll help you out with it. I saw a good example of somewhere, but cannot find it. There is also an options to make like these little circles some people do on their websites.

<img width="866" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/de22ea4a-4464-41a4-a729-b346108ab0dd">

If someone has ideas, please share with us

**Comment by SerhiiCho** [comment]
1. We should fetch them from GitHub in real time, instead we should just create a table and update the contributors list once a day.
2. We can make so that when you click on contributor, it will redirect to a GitHub profile
3. We can display them in random order so that it doesn't matter whether you did 1 or 100 contributors.

### Contributors table
As for a contributors table, maybe 3 columns is enough, since we can get the profile URL like this: `https://github.com/{$username}`.
| id  | username  |  avatar_url |
| -- | --------- | ---------- |
| 1 | brendt | https://avatars.githubusercontent.com/u/6905297 |

**Comment by brendt** [comment]
I was even thinking: why not store it in a JSON file and commit it into the repo? Whenever someone contributes for the first time, they can add their data to it?

**Comment by SerhiiCho** [comment]
Great idea, much more simpler

**Comment by brendt** [comment]
Fixed. I've added a list on the about page. Maybe there's a better place, I think it's ok for now

<img width="687" alt="Screenshot 2023-08-30 at 07 25 06" src="https://github.com/brendt/rfc-vote/assets/6905297/7c3f01dd-d7c5-4574-a107-32c1804f94f8">
