### ISSUE TITLE
Seeding takes too much time

### ISSUE THREAD

**Issue by Erol314** [brendt/rfc-vote#173]
So, during installation I noticed that seeding was taking way too much time (~10-25 mins). which is a lot, considering more tables will eventually appear (comments for example) which will increase the time even more.

Question: Does it seed slow on your local too?

During brief investigation I think this is because of Factories needing to remember/check unique generated keys when new entity created.
[1] https://stackoverflow.com/a/72488945

- I will try to make this in chunks 
- I will try to replace create calls with make, providing the id value manually, in a for loop.

**Comment by vsergiu93** [comment]
Last time I did a seed it took less than a minute, I will retry today and post here my findings.

**Comment by Erol314** [comment]
> Last time I did a seed it took less than a minute, I will retry today and post here my findings.

If its less than i minute clearly I did something wrong))

**Comment by MohammadAlhallaq** [comment]
just did migrate:fresh --seed
toke less than 5 seconds!

**Comment by vsergiu93** [comment]
@Erol314 what is your setup? I mean do you use windows/mac/linux? I guess you are using sail to develop locally as you submitted a pr to improve the docs related to that.

**Comment by Erol314** [comment]
ok, have no idea what was yesterday with my laptop, 
can confirm that it does seed in under 10 sec. 
Closing?
Hmm just noticed @SerhiiCho  comment...

**Comment by SerhiiCho** [comment]
@Erol314 I don't, I just use `php artisan serve` without containers

**Comment by Erol314** [comment]
Ok, since i dont have this issue anymore, and cant reproduce it, closing.

**Comment by Erol314** [comment]
actually, @SerhiiCho can you try it with sail and containers? It has to be easy to install. Just make sure DB_HOST points to service names, line in env.example.

**Comment by SerhiiCho** [comment]
Okay, I'll try it in 10 minutes

**Comment by Erol314** [comment]
> I get this error while installing sail: `31.71 E: Unable to locate package google-chrome-stable` I guess you need google chrome for this, I didn't know that. I'm not gonna install Chrome on my laptop (I don't trust Google). Is there a way to install it without google-chrome-stable? With docker you can say: `--no-install-recommends google-chrome-stable`, but I don't know how to do it with `php artisan sail:install`.
> 
> I'll try to install Chromium instead of Google Chrome, I think it will solve the issue.

https://github.com/brendt/rfc-vote#macos

**Comment by SerhiiCho** [comment]
Yeah, I've tried these variables:

```bash
CHROME_BINARY_PATH=
NODE_BINARY_PATH=/opt/homebrew/bin/node
NPM_BINARY_PATH=/opt/homebrew/bin/npm
```

**Comment by Erol314** [comment]
> Yeah, I've tried these variables:
> 
> ```shell
> CHROME_BINARY_PATH=
> NODE_BINARY_PATH=/opt/homebrew/bin/node
> NPM_BINARY_PATH=/opt/homebrew/bin/npm
> ```

hmm, can you comment out CHROME_BINARY_PATH= , node and npm are enough. afaik

**Comment by SerhiiCho** [comment]
I've tried, it didn't work. I also tried:

```
CHROME_BINARY_PATH=/opt/homebrew/bin/chromium
NODE_BINARY_PATH=/opt/homebrew/bin/node
NPM_BINARY_PATH=/opt/homebrew/bin/npm
```

still `37.20 E: Unable to locate package google-chrome-stable`. Sail assumes I'm gonna use laravel dusk, which I'm not. I wish you could tell that

**Comment by SerhiiCho** [comment]
https://github.com/laravel/homestead/issues/1732#issuecomment-1024992737

> The short answer here is Dusk doesn't support ARM Linux.

**Comment by SerhiiCho** [comment]
I think that Laravel Dusk doesn't support ARM architecture

**Comment by Erol314** [comment]
> I think that Laravel Dusk doesn't support ARM architecture

comment out browsershot in services.php  this shall work.

**Comment by vsergiu93** [comment]
@SerhiiCho You don't need to run `php artisan sail:install` this command is only first time when sail creates the docker-compose.yml file. 

The steps from [local dev](https://github.com/brendt/rfc-vote#local-development) should be enough. 

Chrome is required by browsershot/puppeteer but it doesn't have to be installed directly on your machine, if you look [here](https://github.com/brendt/rfc-vote/blob/e2c308cc58a642992fe5471b94d104b92336bca6/docker/8.2/Dockerfile#L32) you can see that I already installed this in the docker image at build time.

I think I know why is not working for you, basically this [line](https://github.com/brendt/rfc-vote/blob/e2c308cc58a642992fe5471b94d104b92336bca6/docker/8.2/Dockerfile#L21) specifies to be only amd64 architecture, and as far as I know chrome does not work on arm architecture yet.

I can try to change from chrome to chromium. As far as I know puppeteer should work with chromium as well.

Btw since your are on mac  have you looked at this https://herd.laravel.com/?

**Comment by SerhiiCho** [comment]
I don't because there is no way to install php extensions yet, I want to have a power over installing extensions

**Comment by SerhiiCho** [comment]
> Chrome is required by browsershot/puppeteer but it doesn't have to be installed directly

Thanks, I'll try again tomorrow

**Comment by brendt** [comment]
Could you try `BRWOSERSHOT_FAKE=true` in your .env ?

**Comment by brendt** [comment]
Regarding Browsershot on ARM: it works, but I had to manually specify the node and npm paths, which I installed with nvm (https://github.com/nvm-sh/nvm). 

```
NODE_BINARY_PATH=/Users/brent/.nvm/versions/node/v20.5.0/bin/node
NPM_BINARY_PATH=/Users/brent/.nvm/versions/node/v20.5.0/bin/npm
```

The chrome path is the default for me, I simply installed it with `brew install chromium`

Nevertheless, you want browsershot_fake enabled during seeding ;)

**Comment by SerhiiCho** [comment]
The error is still the same for me: `36.05 E: Unable to locate package google-chrome-stable`

It doesn't matter what I run, `php artisan sail:install` or `./vendor/bin/sail up`, the error is still the same. So I went to a Dockerfile and removed the chrome installation from it, and it worked.

**Comment by SerhiiCho** [comment]
Running `time ./vendor/bin/sail artisan migrate:fresh --seed` returned me this:

```bach
./vendor/bin/sail artisan migrate:fresh --seed  0.43s user 0.21s system 11% cpu 5.409 total
```

Which means that migrations with seeding took 5.5 seconds... crazy, locally it takes almost 5 minutes for me. I gotta start using Sail

**Comment by SerhiiCho** [comment]
Can you guys remove [this](https://github.com/brendt/rfc-vote/blob/main/docker/8.2/Dockerfile#L21) line from the Dockerfile and `google-chrome-stable` from [this](https://github.com/brendt/rfc-vote/blob/main/docker/8.2/Dockerfile#L32C8-L32C28) line? Is it gonna effect something? We're not using Dusk anyways

**Comment by vsergiu93** [comment]
@SerhiiCho google-chrome-stable is not used for Dusk, it is used for browsershot which is used to generate that meta image for an rfc. I had a look last night to see if I can use chromium but I wasn't able to, I will have to give it another try.

So I'm using that for the meta image generation job, that's why I added it to docker file, I wanted the sail experience to contain everything set up and read to start, but I failed to account for mac arm based machines.

I'm personally working on windows with wsl2 running everything in containers :D.

Just so that is clear, the idea with sail was that it will install all the necessary dependencies and all you have to do as a developer is to just run the commands to start everything.

**Comment by SerhiiCho** [comment]
Thanks for the explanation @vsergiu93, I've used docker for 4 years myself for everything but Laravel because it always seemed too complex before Sail was a thing. Thanks again for expaining

**Comment by vsergiu93** [comment]
Yes, sail makes things a bit easier, I have configured a custom solution of a different project, that worked well, but anytime you wanted to run migrations or anything like that you will have to run some docker command to ssh in to the laravel container, sail makes this easier because you just write `sail artisan migrate:fresh --seed` and everything is resolved magically :D.

In any case we need to find a solution to make this sail solution work for everyone, as far as I know chrome has no build for arms cpus, which obviously includes mac m1, m2, and, as far as I read on the web chromium is available on arm architecture as well, therefore we need to look into installing chromium instead of chrome in the docker file.

As I wrote above, I tried last night, but it seems that ubuntu by default installs chromium-browser as a snap, not sure if that is ok I need to do some more testing.
