### ISSUE TITLE
Improve user ‍`f‍lair` system

### ISSUE THREAD

**Issue by alirezasalehizadeh** [brendt/rfc-vote#193]
I think the current user flair system could be improved.

* Explaining badge: As mentioned in #183, we need to have a better explaining for each badge.

* Multiple badge: Suppose a member of `Symfony` contributes to the source code of `rfc-vote`. Is it possible to insert the `symfony` and `contributor` badge for him?

In my opinion, it is better to consider a separate table for Flair so that users can have a few badges with related explanations.

**Comment by brendt** [comment]
Thanks for thinking along, I appreciate it :) 

I intentionally kept it simple. I agree that a user could belong to multiple badges, but their goal isn't to describe a user as accurately as possible. It's meant to 

1. have prominent community members stand out in the arguments
2. ensure that these users are real people, which is why they are manually approved

I feel that the current system satisfies those requirements. I agree that we need better descriptions, but they are easily added in the `UserFlair` enum. 

So, since #183 is already open, I think we can close this issue. However, feel free to continue the discussion, maybe there are some aspects I'm missing that might warrant a more complex system.
