### ISSUE TITLE
New RFC email gets sent wen unpublished

### ISSUE THREAD

**Issue by Plytas** [brendt/rfc-vote#236]
Because new rfc emails are being sent on creation, it's possible to create an unpublished RFC through admin and the emails are being sent, which I believe should only happen when RFC is actually published.

I would suggest to implement `RfcPublished` event and handle email sending through listener. We could listen to rfc saved event and check if it is now published and was previously not, then fire `RfcPublished` event.

Also, `resources/views/vendor/mail/text/header.blade.php` expects `$url` parameter, so I think we should pass it to `resources/views/emails/new-rfc.blade.php` header component like this, otherwise it crashes if mailable tries to render to text.

<img width="913" alt="image" src="https://github.com/brendt/rfc-vote/assets/17316322/348a303b-0b18-4b7c-afbb-59a384d73c91">

**Comment by brendt** [comment]
Valid catch. However, I was actually thinking about removing the concept of "unpublished RFCs":

- If we ever import RFCs from internals, I rather have a dedicated model `PendingRfc`, so that we don't clutter the RFC model even further. 
- If we ever manually add an RFC, it's ok for it to be published immediately.

If we decide we want to keep draft RFCs, I think it's best to add a status field, and hook into status changes for sending mails.

What do others think?

**Comment by brendt** [comment]
Closing for now, will revisit when we're finishing RFC importing
