### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#405]
Visiting the RFC detail page, while logged in with a user (maybe only admin users, need to verify), leads to a memory overflow error on the production server. The same problem doesn't happen locally :/ 

Need to further investigate.

**Comment by SerhiiCho** [comment]
I found the issue

**Comment by SerhiiCho** [comment]
This is why I don't like Livewire, it's impossible to debug when an error happens. It just says that memory overflow, even though we use around 100 MB on the page

**Comment by SerhiiCho** [comment]
The only way you can try to debug, is to get the dump of the database, and import everything locally. There is a big chance that you will be able to reproduce it.

**Comment by brendt** [comment]
I did copy the database, but it didn't happen locally :(

**Comment by vsergiu93** [comment]
Hey @brendt @SerhiiCho , I tried to debug this locally but not sure 100% sure I understand what is happening here.

Here is what I did, I changed the seeder class to create a lot of arguments and votes, And I have this monster 
![image](https://github.com/brendt/rfc-vote/assets/5923843/a79d4b14-849d-46b4-aad7-a00ca12cd998)
I know that is not the same as the real db, but I think we are not really interested in the exact db but rather the amount of data.

Here are my findings so far: 

1. Locally in dev mode the detail page of rfc is quite slow with this amount of data: 
   - 9+ seconds as logged in as admin 
   - 4 + seconds as normal user 
   - 1.2 seconds as guest
   so it's clear that we are doing something extra for logged in user and especially for admins
2. I tried profiling the app with xdebug: 
   - This is sorted by memory: 
![image](https://github.com/brendt/rfc-vote/assets/5923843/821a2c1f-8d00-4102-9734-17695ba0b613)
   - This is sorted by calls: 
![image](https://github.com/brendt/rfc-vote/assets/5923843/4da8fda2-d1d3-45c7-b80e-6edd940140f4)
   - This is sorted by own time: 
   ![image](https://github.com/brendt/rfc-vote/assets/5923843/06da8eb0-613e-4e49-a795-3570a6e2f7c0)
3. I noticed that we are loading quite a lot of models especially for logged in users:
    - Logged in as admin: 
     ![image](https://github.com/brendt/rfc-vote/assets/5923843/92f75add-c192-4a3e-9e65-c7783afacf7d)
    - Logged in as guest:
    ![image](https://github.com/brendt/rfc-vote/assets/5923843/99ad9581-4ae6-4ce8-ac09-d2c2342ace8f)
   - Logged in as non admin:
   ![image](https://github.com/brendt/rfc-vote/assets/5923843/8ad0f288-4f06-4866-b139-7aa318dd6a15)


Not 100% sure where the problem is, tried to comment out some templates indeed I saw some improvement in load time and some minor improvement in terms of models loaded.

I'm wondering, if this lines [here ](https://github.com/brendt/rfc-vote/blob/be0af2e6966e62d855f753f70c66bfae79a59805/app/Http/Controllers/RfcDetailController.php#L19-L31) would increase the load of the server by a lot if the currently authenticated user has quite a lot of arguments and viewedArguments, (I'll try to test this).

**Comment by brendt** [comment]
Would it be an idea to gradually refactor out livewire? Starting with this page? I'm not sure about the implications though, since there's quite a lot going on, and my Vue knowledge is **very** rusty :/ 

About the memory limit: I'd need to check when I'm at my desk. But I'm pretty sure we've hit the root of the problem: we're loading in way too much data, especially when admin users are logged in. Thanks a lot for the debugging @vsergiu93 , awesome work!

**Comment by brendt** [comment]
I've update the title of this issue to better reflect the problem

**Comment by brendt** [comment]
By the way, Livewire might not be the root cause of the issue. We're loading quite a lot of model relations in memory, so that we don't need to perform any additional queries. For example: every argument loads each vote, and for that vote again the argument, so that we have easy access to data without having to worry about additional queries. Of course, at the cost of memory.

As an example, one of the features we need this for, is to check whether a user has voted for an argument. The better approach here is to have a separate database table to simply lists per user which arguments they voted for; it's a simple `user_id` `argument_id` table, which can be indexed and is super fast + low on memory. 

I believe these kinds of optimisations will help us solve the root problem.

**Comment by vsergiu93** [comment]
Hey @brendt, just to be clear I'm not suggesting to move away from Livewire, I was just expressing that I'm not sure if I like it or not, but that is just me.
I think the whole refc detail page needs to be refactored, but indeed I would start with lowering as much as possible the amount of eloquent models loaded. 
Also, if you give some of the relevant php.ini values, like memory_limit I can try to have the same locally.

**Comment by brendt** [comment]
@vsergiu93 it's 512M, but that's the same limit I have locally, and I don't encounter any problems there :/

**Comment by vsergiu93** [comment]
@brendt, Hmm this is weird, in any case I'll try to put this limit on my end as well, but It will be afternoon, in any case we kind of know now what the problem is. I just want to have going forward the more or less the same environment as in prod.

**Comment by brendt** [comment]
I did some more testing and made some optimizations: https://github.com/brendt/rfc-vote/commit/6cd8d20d5a4030333f6c60647e6ac91463555162

I temporarily disabled argument views, since they are very poorly implemented at the moment. 

However, even with these changes, production is still crashing, only when logged in as an admin user. It's super annoying that I can't seem to reproduce the problem locally: I have the production database, am logged in as the admin user, and experience no problems. The debug bar also doesn't show an excessive amount of models in memory or queries. 

Just writing it down here in case someone's debugging as well

**Comment by SerhiiCho** [comment]
It might be the new two column layout uses too much memory. What if we unroll changes before that pull request #404? If it solves the issue that abandon those changes, it's not worth it

**Comment by brendt** [comment]
Ok good idea :) do you need any help with that?

**Comment by SerhiiCho** [comment]
It's done! I undo all the 2 column layout changes in [this](https://github.com/brendt/rfc-vote/pull/449) pull request. I already merged it

**Comment by SerhiiCho** [comment]
We'll see if it works on production

**Comment by brendt** [comment]
Unfortunately the problem's still there. I'll try to take a closer look at it this week :)

**Comment by brendt** [comment]
Did some more testing. The two biggest issues are these:

- Related RFCs at the bottom of the page — this can probably be fixed easily
- Unviewed arguments — this is more difficult to solve and will need a proper refactor

I've disabled both for now:

https://github.com/brendt/rfc-vote/commit/bb58441fd933ab609f4c0def9b99f3da9da39cdd

**Comment by SerhiiCho** [comment]
I think I've fixed the issue in PR #457. 

I feel like this fixes memory issue on arguments page. I've noticed that `options.blade.php` blade component was causing memory issues for some reason. After this PR, memory usage dropped in 5 times if the `debug bar` is not lying. I hope it will solve issue on production server as well

**Comment by brendt** [comment]
Well it's definitely much faster now! Within acceptable range for admin users 🥳
