### ISSUE TITLE
Editor for arguments

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#45]
Arguments support markdown, it makes sense to have some kind of editor like https://github.com/Ionaru/easy-markdown-editor

**Comment by vsergiu93** [comment]
If no one is working on this yet then I would like to give it a try.

**Comment by brendt** [comment]
Sure, go ahead!

**Comment by vsergiu93** [comment]
Well, I gave it a try, it was painful. It is the first time I work with livewire and alpine.js and it is quite confusing. :) 
Never the less, I managed to create a POC [PR](https://github.com/brendt/rfc-vote/pull/80), obviously there is room for improvement, for example it would be nice tough to extract this somehow as it's own component so that it can be easily reused.


Some examples of how it looks like right now: 
Editor screen
![image](https://github.com/brendt/rfc-vote/assets/5923843/2123d6cd-085b-451b-85a5-971bd5868519)

Preview screen
![image](https://github.com/brendt/rfc-vote/assets/5923843/c6044cc7-cb40-4350-bcb5-e88485403293)

The PR is in draft as I'm not really happy with the end result.

**Comment by brendt** [comment]
Any way I can help you? Let me know :)

**Comment by vsergiu93** [comment]
Not sure, I mean feel free to jump in either in code review with suggestions or just push some changes directly to my PR if explaining the changes required would take to much or your time.
I'm new to liveware, alpine.js and laravel components. I always used laravel as an json api back-end so all of this is bit confusing to me. But, I do wish to learn as they seem to be quite powerful in the right hands.

**Comment by brendt** [comment]
I looked pretty nice, thanks for investing your time in it :) I've deployed everything to production
